<?php echo $header; ?>
<style>
.egp{--red:#ef1b23;--ink:#201715;--orange:#f1a323;--text:#3f3b39;--muted:#77716d;--soft:#f8f6f3;--line:#eaded4;background:#fff;color:var(--text);padding-bottom:24px}.egp *{box-sizing:border-box}.egp a{text-decoration:none}.egp-shell{width:min(1240px,calc(100% - 42px));margin:0 auto}.egp-crumb{display:flex;gap:9px;align-items:center;flex-wrap:wrap;padding:18px 0;color:#777;font-size:13px}.egp-crumb a{color:#777}.egp-crumb a:hover{color:var(--red)}.egp-crumb i{font-style:normal;color:#bbb}
.egp-hero{display:grid;grid-template-columns:1.08fr .92fr;min-height:390px;overflow:hidden;border:1px solid var(--line);border-radius:27px;background:#fff}.egp-hero__copy{display:flex;flex-direction:column;justify-content:center;padding:46px 52px}.egp-label{display:flex;align-items:center;gap:10px;color:var(--red);font-size:11px;font-weight:900;letter-spacing:.15em}.egp-label:before{content:"";width:28px;height:2px;background:linear-gradient(90deg,var(--red),var(--orange))}.egp h1{margin:15px 0 20px;color:#44413f;font-size:clamp(36px,3.7vw,52px);line-height:1.07;letter-spacing:-.04em}.egp-meta{display:flex;align-items:center;gap:9px;flex-wrap:wrap;color:#837d78;font-size:12px}.egp-meta i{width:4px;height:4px;border-radius:50%;background:var(--orange)}.egp-hero__media{display:flex;min-width:0;overflow:hidden}.egp-hero__media img{display:block;width:100%;height:100%;object-fit:cover}.egp-hero__fallback{display:flex;flex-direction:column;justify-content:center;width:100%;height:100%;padding:28px;color:#fff;background:linear-gradient(145deg,#191513,#281b17)}.egp-hero__fallback small{color:var(--orange);font-weight:900;letter-spacing:.14em}.egp-hero__fallback strong{max-width:380px;margin-top:13px;font-size:29px;line-height:1.16}
.egp-layout{display:grid;grid-template-columns:minmax(0,820px) 300px;justify-content:space-between;gap:54px;align-items:start;padding:50px 0}.egp-content{min-width:0;color:#3f3b39;font-size:16px;line-height:1.78}.egp-content>:first-child{margin-top:0}.egp-content h1{display:none!important}.egp-content h2{position:relative;margin:40px 0 15px;padding-top:18px;border-top:1px solid var(--line);color:#3a3735;font-size:28px;line-height:1.22;letter-spacing:-.025em}.egp-content h2:before{content:"";position:absolute;left:0;top:-1px;width:56px;height:3px;background:linear-gradient(90deg,var(--red),var(--orange))}.egp-content h3{margin:27px 0 10px;color:#373331;font-size:20px;line-height:1.3}.egp-content p{margin:0 0 17px}.egp-content a{color:var(--red);font-weight:700}.egp-content ul,.egp-content ol{margin:0 0 22px;padding-left:23px}.egp-content li{margin:6px 0}.egp-content li p{margin:0}.egp-content hr{height:1px;margin:32px 0;border:0;background:var(--line)}.egp-content blockquote{margin:24px 0;padding:18px 20px;border-left:4px solid var(--orange);border-radius:0 11px 11px 0;background:#fff8ea}.egp-content img{display:block!important;width:100%!important;height:460px!important;max-width:100%!important;margin:20px auto 30px!important;padding:10px!important;border:1px solid var(--line)!important;border-radius:15px!important;background:#f3f0ec!important;object-fit:contain!important}.egp-content table{display:block;width:100%;max-width:100%;margin:23px 0;overflow-x:auto;border-collapse:collapse;font-size:13px}.egp-content th,.egp-content td{min-width:145px;padding:11px 12px;border:1px solid var(--line);text-align:left;vertical-align:top}.egp-content th{background:var(--ink);color:#fff}.egp-content tr:nth-child(even) td{background:var(--soft)}
.egp-side{position:sticky;top:105px;display:grid;gap:13px}.egp-box{padding:23px;border:1px solid var(--line);border-radius:18px;background:#fff}.egp-box--dark{border:0;background:linear-gradient(145deg,#191513,#281b17);color:#fff}.egp-box small{color:var(--orange);font-size:10px;font-weight:900;letter-spacing:.13em}.egp-box h2{margin:10px 0 9px;color:inherit;font-size:21px;line-height:1.22}.egp-box p{margin:0 0 16px;color:var(--muted);font-size:12.5px;line-height:1.62}.egp-box--dark p{color:#d4ccc8}.egp-btn{display:flex;align-items:center;justify-content:center;min-height:43px;margin-top:8px;padding:0 13px;border-radius:10px;font-size:12px;font-weight:900}.egp-btn--red{background:var(--red);color:#fff}.egp-btn--red:hover{background:#ce151c;color:#fff}.egp-btn--light{border:1px solid var(--line);background:#fff;color:var(--ink)}.egp-back{display:flex;align-items:center;justify-content:space-between;gap:12px;color:#34302e;font-size:13px;font-weight:850}.egp-back b{color:var(--red)}.egp-share{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.egp-share a,.egp-share button{display:inline-flex;align-items:center;gap:6px;min-height:38px;padding:0 14px;border:1px solid var(--line);border-radius:9px;background:#fff;color:var(--ink);font-family:inherit;font-size:12px;font-weight:800;cursor:pointer;transition:.15s}.egp-share a:hover,.egp-share button:hover{border-color:var(--red);color:var(--red)}.egp-toc{list-style:none;margin:0;padding:0;display:grid;gap:10px}.egp-toc a{display:flex;align-items:flex-start;gap:9px;color:var(--ink);font-size:13px;font-weight:700;line-height:1.4}.egp-toc a:hover{color:var(--red)}.egp-toc a:hover em{border-color:var(--red);color:var(--red)}.egp-toc em{flex-shrink:0;display:inline-flex;align-items:center;justify-content:center;width:20px;height:20px;margin-top:1px;border:1px solid var(--line);border-radius:50%;color:var(--muted);font-size:9px;font-weight:900;font-style:normal;transition:.15s}
.egp-end{display:flex;align-items:center;justify-content:space-between;gap:26px;margin-bottom:56px;padding:29px 33px;border:1px solid var(--line);border-radius:21px;background:var(--soft)}.egp-end h2{margin:7px 0 5px;color:#3d3937;font-size:26px}.egp-end p{margin:0;color:var(--muted);font-size:13px}.egp-end__actions{display:flex;gap:8px;flex-shrink:0}
.egp-related{padding:6px 0 46px}.egp-related h2{margin:0 0 20px;color:#3a3735;font-size:26px;letter-spacing:-.02em}.egp-related__grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.egp-related__card{display:flex;flex-direction:column;overflow:hidden;border:1px solid var(--line);border-radius:17px;background:#fff;color:#2d2927;transition:.2s}.egp-related__card:hover{transform:translateY(-3px);border-color:#ddcabe;box-shadow:0 14px 30px rgba(37,25,18,.07)}.egp-related__image{display:block;aspect-ratio:1/1;overflow:hidden;background:#f2efeb}.egp-related__image img{display:block;width:100%;height:100%;object-fit:cover;transition:transform .3s ease}.egp-related__card:hover .egp-related__image img{transform:scale(1.04)}.egp-related__body{padding:16px}.egp-related__body span{color:#8b837d;font-size:10.5px}.egp-related__body h3{margin:8px 0 0;font-size:15px;line-height:1.32;letter-spacing:-.01em}
@media(max-width:940px){.egp-hero{grid-template-columns:1fr}.egp-hero__media{min-height:340px}.egp-layout{grid-template-columns:1fr}.egp-side{position:static;grid-template-columns:1fr 1fr}.egp-end{align-items:flex-start;flex-direction:column}.egp-end__actions{width:100%}.egp-end__actions .egp-btn{flex:1}.egp-related__grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:580px){.egp-shell{width:min(100% - 28px,1240px)}.egp-crumb{padding:14px 0;font-size:12px}.egp-hero{border-radius:20px}.egp-hero__copy{padding:30px 24px}.egp h1{font-size:34px}.egp-hero__media{min-height:0}.egp-hero__media img{height:auto}.egp-layout{gap:36px;padding:35px 0}.egp-content{font-size:15.5px;line-height:1.74}.egp-content h2{margin-top:34px;font-size:25px}.egp-content h3{font-size:19px}.egp-content img{height:285px!important;margin:16px auto 23px!important;padding:7px!important}.egp-side{grid-template-columns:1fr}.egp-end{margin-bottom:84px;padding:25px 22px}.egp-end__actions{flex-direction:column}.egp-end__actions .egp-btn{width:100%}.egp-related__grid{grid-template-columns:1fr}}
</style>
<main class="egp"><div class="egp-shell">
  <nav class="egp-crumb" aria-label="Sayfa yolu"><?php foreach ($breadcrumbs as $i => $breadcrumb) { ?><?php if ($i) { ?><i>/</i><?php } ?><?php if ($i + 1 < count($breadcrumbs)) { ?><a href="<?php echo htmlspecialchars($breadcrumb['href'], ENT_QUOTES, 'UTF-8'); ?>"><?php echo htmlspecialchars($breadcrumb['text'], ENT_QUOTES, 'UTF-8'); ?></a><?php } else { ?><span aria-current="page"><?php echo htmlspecialchars($breadcrumb['text'], ENT_QUOTES, 'UTF-8'); ?></span><?php } ?><?php } ?></nav>
  <?php echo $content_top; ?>
  <article>
    <header class="egp-hero"><div class="egp-hero__copy"><span class="egp-label">PREFABRİK YAPI REHBERİ</span><h1><?php echo htmlspecialchars($heading_title, ENT_QUOTES, 'UTF-8'); ?></h1><div class="egp-meta"><span>Egeser Bilgi Merkezi</span><?php if ($date) { ?><i></i><span><?php echo htmlspecialchars($date, ENT_QUOTES, 'UTF-8'); ?></span><?php } ?><?php if ($date_modified) { ?><i></i><span>Güncellendi: <?php echo htmlspecialchars($date_modified, ENT_QUOTES, 'UTF-8'); ?></span><?php } ?><i></i><span><?php echo (int)$views; ?> görüntülenme</span></div></div><div class="egp-hero__media"><?php if ($image) { ?><img src="<?php echo htmlspecialchars($image, ENT_QUOTES, 'UTF-8'); ?>" alt="<?php echo htmlspecialchars($heading_title, ENT_QUOTES, 'UTF-8'); ?>" width="640" height="640"><?php } else { ?><div class="egp-hero__fallback"><small>EGESER PREFABRİK</small><strong>Teknik bilgiyi doğru proje kararına dönüştürün.</strong></div><?php } ?></div></header>
    <div class="egp-layout"><div class="egp-content"><?php echo $description; ?></div><aside class="egp-side"><?php if (!empty($toc) && count($toc) >= 2) { ?><div class="egp-box"><small>İÇİNDEKİLER</small><h2>Bu yazıda</h2><ul class="egp-toc"><?php foreach ($toc as $i => $item) { ?><li><a href="#<?php echo htmlspecialchars($item['id'], ENT_QUOTES, 'UTF-8'); ?>"><em><?php echo $i + 1; ?></em><span><?php echo htmlspecialchars($item['text'], ENT_QUOTES, 'UTF-8'); ?></span></a></li><?php } ?></ul></div><?php } ?><div class="egp-box egp-box--dark"><small>PROJENİZ İÇİN</small><h2>İhtiyacınızı birlikte değerlendirelim.</h2><p>Yaklaşık m², oda planı ve uygulama bölgesini paylaşmanız yeterli.</p><a class="egp-btn egp-btn--red" href="<?php echo htmlspecialchars($contact_url, ENT_QUOTES, 'UTF-8'); ?>">Teklif / Bilgi Al</a><a class="egp-btn egp-btn--light" href="<?php echo htmlspecialchars($whatsapp_url, ENT_QUOTES, 'UTF-8'); ?>" target="_blank" rel="noopener">WhatsApp’tan Yaz</a></div><div class="egp-box"><small>PAYLAŞ</small><h2>Bu yazıyı paylaşın.</h2><div class="egp-share"><a href="https://wa.me/?text=<?php echo rawurlencode($heading_title . ' - ' . $canonical); ?>" target="_blank" rel="noopener">WhatsApp</a><a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo rawurlencode($canonical); ?>" target="_blank" rel="noopener">Facebook</a><a href="https://twitter.com/intent/tweet?text=<?php echo rawurlencode($heading_title); ?>&amp;url=<?php echo rawurlencode($canonical); ?>" target="_blank" rel="noopener">X</a><a href="https://www.linkedin.com/sharing/share-offsite/?url=<?php echo rawurlencode($canonical); ?>" target="_blank" rel="noopener">LinkedIn</a><button type="button" class="egp-share__copy" data-egp-copy="<?php echo htmlspecialchars($canonical, ENT_QUOTES, 'UTF-8'); ?>">Linki Kopyala</button></div></div><div class="egp-box"><a class="egp-back" href="<?php echo htmlspecialchars($blog_url, ENT_QUOTES, 'UTF-8'); ?>">Tüm Rehberlere Dön <b>→</b></a><a class="egp-btn egp-btn--light" href="<?php echo htmlspecialchars($models_url, ENT_QUOTES, 'UTF-8'); ?>">Prefabrik Yapıları İncele</a></div></aside></div>
  </article>
  <?php if (!empty($related_posts)) { ?>
  <section class="egp-related"><h2>Bunları da okuyabilirsiniz</h2><div class="egp-related__grid"><?php foreach ($related_posts as $related) { ?><a class="egp-related__card" href="<?php echo htmlspecialchars($related['href'], ENT_QUOTES, 'UTF-8'); ?>"><?php if (!empty($related['image'])) { ?><span class="egp-related__image"><img src="<?php echo htmlspecialchars($related['image'], ENT_QUOTES, 'UTF-8'); ?>" alt="<?php echo htmlspecialchars($related['title'], ENT_QUOTES, 'UTF-8'); ?>" loading="lazy" width="640" height="640"></span><?php } ?><span class="egp-related__body"><?php if ($related['date']) { ?><span><?php echo htmlspecialchars($related['date'], ENT_QUOTES, 'UTF-8'); ?></span><?php } ?><h3><?php echo htmlspecialchars($related['title'], ENT_QUOTES, 'UTF-8'); ?></h3></span></a><?php } ?></div></section>
  <?php } ?>
  <?php echo $content_bottom; ?>
  <section class="egp-end"><div><span class="egp-label">EGESER PREFABRİK</span><h2>Projeniz için ilk adımı atın.</h2><p>Teknik kapsam, saha ve teslim seçeneklerini birlikte değerlendirelim.</p></div><div class="egp-end__actions"><a class="egp-btn egp-btn--light" href="<?php echo htmlspecialchars($models_url, ENT_QUOTES, 'UTF-8'); ?>">Modelleri İncele</a><a class="egp-btn egp-btn--red" href="<?php echo htmlspecialchars($contact_url, ENT_QUOTES, 'UTF-8'); ?>">Teklif Al</a></div></section>
</div></main>
<script type="application/ld+json"><?php echo json_encode($schema, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT); ?></script>
<script type="application/ld+json"><?php echo json_encode($breadcrumb_schema, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT); ?></script>
<script>
(function(){
  var buttons = document.querySelectorAll('.egp-share__copy');

  for (var i = 0; i < buttons.length; i++) {
    buttons[i].addEventListener('click', function() {
      var url = this.getAttribute('data-egp-copy');
      var label = this;
      var original = label.textContent;

      function done(ok) {
        label.textContent = ok ? 'Kopyalandı ✓' : 'Kopyalanamadı';
        setTimeout(function() { label.textContent = original; }, 2000);
      }

      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(url).then(function() { done(true); }, function() { done(false); });
      } else {
        try {
          var tmp = document.createElement('textarea');
          tmp.value = url;
          document.body.appendChild(tmp);
          tmp.select();
          document.execCommand('copy');
          document.body.removeChild(tmp);
          done(true);
        } catch (e) {
          done(false);
        }
      }
    });
  }
})();
</script>
<?php echo $footer; ?>
