<?php echo $header; ?>
<?php $project = (isset($egeser_project) && is_array($egeser_project)) ? $egeser_project : array(); ?>
<main id="content" class="eg-page eg-project-detail">
  <div class="eg-container">
    <nav class="eg-breadcrumb" aria-label="Breadcrumb"><ol><?php foreach ($breadcrumbs as $breadcrumb) { ?><li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a></li><?php } ?></ol></nav>
    <header class="eg-project-detail__hero">
      <div class="eg-project-detail__content"><span class="eg-section__eyebrow"><?php echo !empty($project['type']) ? $project['type'] : 'TAMAMLANAN PROJE'; ?></span><h1><?php echo $heading_title; ?></h1><?php if (!empty($project['summary'])) { ?><p><?php echo $project['summary']; ?></p><?php } ?><div class="eg-project-detail__meta"><?php if (!empty($project['location'])) { ?><span><strong>Lokasyon</strong><?php echo $project['location']; ?></span><?php } ?><?php if (!empty($project['area'])) { ?><span><strong>Alan</strong><?php echo $project['area']; ?></span><?php } ?><?php if (!empty($project['plan'])) { ?><span><strong>Plan</strong><?php echo $project['plan']; ?></span><?php } ?><?php if (!empty($project['year'])) { ?><span><strong>Yıl</strong><?php echo $project['year']; ?></span><?php } ?></div><div class="eg-actions"><a class="eg-btn eg-btn--primary" href="#eg-project-detail-offer">Benzer Proje İçin Teklif Al</a><?php if (!empty($project['whatsapp_url'])) { ?><a class="eg-btn eg-btn--outline" href="<?php echo $project['whatsapp_url']; ?>" target="_blank" rel="noopener noreferrer">WhatsApp'tan Sor</a><?php } ?></div></div>
      <?php if (!empty($project['hero'])) { ?><div class="eg-project-detail__media"><img src="<?php echo $project['hero']; ?>" alt="<?php echo htmlspecialchars(strip_tags($heading_title), ENT_QUOTES, 'UTF-8'); ?>" width="1000" height="720" loading="eager" decoding="async"></div><?php } ?>
    </header>

    <?php if (!empty($project['gallery']) && is_array($project['gallery'])) { ?><section class="eg-project-gallery" aria-labelledby="eg-project-gallery-title"><span class="eg-section__eyebrow">PROJE GÖRSELLERİ</span><h2 id="eg-project-gallery-title">Uygulama Detayları</h2><div class="eg-project-gallery__grid"><?php foreach ($project['gallery'] as $image) { ?><a href="<?php echo $image['popup']; ?>" class="eg-project-gallery__item"><img src="<?php echo $image['thumb']; ?>" alt="<?php echo htmlspecialchars(!empty($image['alt']) ? $image['alt'] : strip_tags($heading_title), ENT_QUOTES, 'UTF-8'); ?>" width="640" height="430" loading="lazy" decoding="async"></a><?php } ?></div></section><?php } ?>

    <?php if (!empty($project['technical']) && is_array($project['technical'])) { ?><section class="eg-project-technical"><span class="eg-section__eyebrow">TEKNİK KAPSAM</span><h2>Projede Uygulanan Çözümler</h2><div class="eg-technical__grid"><?php foreach ($project['technical'] as $item) { ?><article><strong><?php echo $item['name']; ?></strong><span><?php echo $item['value']; ?></span></article><?php } ?></div></section><?php } ?>

    <?php if (!empty($description)) { ?><section class="eg-project-story"><span class="eg-section__eyebrow">PROJE HİKÂYESİ</span><h2><?php echo $heading_title; ?> Uygulaması</h2><div class="eg-richtext"><?php echo $description; ?></div></section><?php } ?>

    <?php if (!empty($project['related']) && is_array($project['related'])) { ?><section class="eg-related-projects"><div class="eg-section__heading"><div><span class="eg-section__eyebrow">BENZER PROJELER</span><h2>İnceleyebileceğiniz Diğer Uygulamalar</h2></div></div><div class="eg-projects-grid"><?php foreach ($project['related'] as $related) { ?><article class="eg-project-archive-card"><a class="eg-project-archive-card__media" href="<?php echo $related['href']; ?>"><?php if (!empty($related['thumb'])) { ?><img src="<?php echo $related['thumb']; ?>" alt="<?php echo htmlspecialchars(strip_tags($related['name']), ENT_QUOTES, 'UTF-8'); ?>" width="640" height="430" loading="lazy" decoding="async"><?php } ?></a><div class="eg-project-archive-card__body"><h3><a href="<?php echo $related['href']; ?>"><?php echo $related['name']; ?></a></h3><a class="eg-section__link" href="<?php echo $related['href']; ?>">Projeyi İncele →</a></div></article><?php } ?></div></section><?php } ?>

    <section id="eg-project-detail-offer" class="eg-category-offer"><div class="eg-offer"><div class="eg-offer__content"><span class="eg-section__eyebrow">TEKLİF</span><h2>Bu Projeye Benzer Bir Yapı Planlayalım</h2><p>Proje detaylarını referans göstererek ihtiyaçlarınızı iletin; ekip size uygun teknik kapsamı ve sonraki adımları değerlendirsin.</p></div><?php if (isset($egeser_lead_form_html)) { echo $egeser_lead_form_html; } else { ?><a class="eg-btn eg-btn--primary" href="index.php?route=information/contact">Proje Teklifi Al</a><?php } ?></div></section>
  </div>
</main>
<script type="application/ld+json"><?php $items=array();$pos=1;foreach($breadcrumbs as $b){$items[]=array('@type'=>'ListItem','position'=>$pos++,'name'=>strip_tags($b['text']),'item'=>$b['href']);}echo json_encode(array('@context'=>'https://schema.org','@type'=>'BreadcrumbList','itemListElement'=>$items),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT); ?></script>
<?php echo $footer; ?>
