<?php if (!empty($egeser_floorplans)) { ?>
<section class="eg-floorplans-v21" id="eg-kat-planlari-v21" aria-labelledby="eg-floorplans-title">
  <div class="eg-floorplans-v21__head">
    <div><span class="eg-floorplans-v21__eyebrow">KAT PLANI</span><h2 id="eg-floorplans-title"><?php echo count($egeser_floorplans) > 1 ? 'Kat planlarını inceleyin.' : 'Planı ilk bakışta inceleyin.'; ?></h2></div>
    <p>Kat planları ürün galerisinden bağımsız yönetilir. Ölçü ve uygulama detayları proje kapsamında netleştirilir.</p>
  </div>
  <?php if (count($egeser_floorplans) > 1) { ?><div class="eg-floorplans-v21__tabs" role="tablist" aria-label="Kat planları"><?php foreach ($egeser_floorplans as $i=>$plan) { ?><button type="button" class="eg-floorplans-v21__tab<?php echo $i===0?' is-active':''; ?>" data-eg-floorplan-tab="<?php echo $i; ?>" role="tab" aria-selected="<?php echo $i===0?'true':'false'; ?>"><?php echo htmlspecialchars($plan['title'], ENT_QUOTES, 'UTF-8'); ?></button><?php } ?></div><?php } ?>
  <div class="eg-floorplans-v21__stage">
    <?php foreach ($egeser_floorplans as $i=>$plan) { ?><figure class="eg-floorplans-v21__panel<?php echo $i===0?' is-active':''; ?>" data-eg-floorplan-panel="<?php echo $i; ?>"<?php echo $i===0?'':' hidden'; ?>>
      <a href="<?php echo $plan['popup']; ?>" target="_blank" rel="noopener" aria-label="<?php echo htmlspecialchars($plan['title'], ENT_QUOTES, 'UTF-8'); ?> planını büyüt">
        <img src="<?php echo $plan['image']; ?>" alt="<?php echo htmlspecialchars($heading_title . ' - ' . $plan['title'], ENT_QUOTES, 'UTF-8'); ?>" loading="lazy" decoding="async">
      </a>
      <figcaption><strong><?php echo htmlspecialchars($plan['title'], ENT_QUOTES, 'UTF-8'); ?></strong><span>Plan görselini büyütmek için tıklayın.</span></figcaption>
    </figure><?php } ?>
  </div>
</section>
<style>
.eg-floorplans-v21{margin:54px 0;padding:30px;border:1px solid #eee4da;border-radius:22px;background:#fffdf9;box-sizing:border-box}.eg-floorplans-v21 *{box-sizing:border-box}.eg-floorplans-v21__head{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(260px,.75fr);gap:40px;align-items:end;margin-bottom:24px}.eg-floorplans-v21__eyebrow{display:block;margin-bottom:8px;font-size:12px;font-weight:800;letter-spacing:.14em;color:#e31e24}.eg-floorplans-v21 h2{margin:0;font-size:34px;line-height:1.08;color:#171717}.eg-floorplans-v21__head p{margin:0;color:#666;line-height:1.65}.eg-floorplans-v21__tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}.eg-floorplans-v21__tab{appearance:none;border:1px solid #e7d8c8;background:#fff;color:#202020;border-radius:999px;padding:10px 16px;font-weight:700;cursor:pointer}.eg-floorplans-v21__tab.is-active{background:#181818;color:#fff;border-color:#181818}.eg-floorplans-v21__stage{position:relative}.eg-floorplans-v21__panel{margin:0}.eg-floorplans-v21__panel>a{display:block;overflow:hidden;border-radius:18px;background:#f6f3ef;border:1px solid #ece3db}.eg-floorplans-v21__panel img{display:block;width:100%;height:auto;max-height:780px;object-fit:contain;margin:auto}.eg-floorplans-v21__panel figcaption{display:flex;justify-content:space-between;gap:18px;padding:14px 4px 0;color:#555}.eg-floorplans-v21__panel figcaption strong{color:#171717}.eg-floorplans-v21__panel figcaption span{font-size:13px}.eg-floorplans-v21__panel[hidden]{display:none!important}@media(max-width:767px){.eg-floorplans-v21{margin:32px 0;padding:18px;border-radius:16px}.eg-floorplans-v21__head{grid-template-columns:1fr;gap:10px}.eg-floorplans-v21 h2{font-size:27px}.eg-floorplans-v21__tabs{display:grid;grid-template-columns:1fr 1fr}.eg-floorplans-v21__tab{width:100%;padding:9px 10px}.eg-floorplans-v21__panel figcaption{display:block}.eg-floorplans-v21__panel figcaption span{display:block;margin-top:4px}}
</style>
<script>(function(){var root=document.getElementById('eg-kat-planlari-v21');if(!root)return;var tabs=root.querySelectorAll('[data-eg-floorplan-tab]');var panels=root.querySelectorAll('[data-eg-floorplan-panel]');for(var i=0;i<tabs.length;i++){tabs[i].addEventListener('click',function(){var key=this.getAttribute('data-eg-floorplan-tab');for(var t=0;t<tabs.length;t++){var on=tabs[t]===this;tabs[t].classList.toggle('is-active',on);tabs[t].setAttribute('aria-selected',on?'true':'false');}for(var p=0;p<panels.length;p++){var show=panels[p].getAttribute('data-eg-floorplan-panel')===key;panels[p].classList.toggle('is-active',show);if(show)panels[p].removeAttribute('hidden');else panels[p].setAttribute('hidden','hidden');}});}/* Eski yanlış kat planı bloğunu yalnızca yeni plan varsa gizle. */var headings=document.querySelectorAll('h1,h2,h3');for(var h=0;h<headings.length;h++){var tx=(headings[h].textContent||'').replace(/\s+/g,' ').trim();if(tx.indexOf('Alanı nasıl kullanacağınızı ilk bakışta görün')!==-1){var sec=headings[h].closest?headings[h].closest('section'):null;if(sec&&sec!==root)sec.style.display='none';}}})();</script>
<?php } ?>
